### ISSUE TITLE
IP Removal Request

### ISSUE THREAD

**Issue by joecorall** [prbutler/EZProxy_IP_Blacklist#1]
Hello,

Please remove the range

131.123.27.0-131.123.27.255

from the blacklist. That IP range is part of the Kent State University Network.

**Comment by prbutler** [comment]
Sorry about that. Will do!

## Cheers, Paul

Paul R Butler, mlis
Library Technologies Support Analyst
Library Information Technology Services (L.I.T.S)
Ball State University<bsu.edu>
Muncie, IN  47306
P: 765.285.8032
E: prbutler@bsu.edumailto:prbutler@bsu.edu

University Libraries...a destination for research, learning, and friends

The University Libraries provide services that support student pursuits for academic success and faculty endeavors for knowledge creation and classroom instruction.

**Comment by prbutler** [comment]
Hi Joe, 
IP range 131.123.27.0-131.123.27.255 has been removed from the blacklist. It looks like this is not a recent addition to the blacklist, but has been a part of the blacklist at least since its move to GitHub. 

The next time I email the listserv I will make them aware of the removal. Thanks for contacting me. 
Cheers, Paul
